In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as seaborn

In [2]:
df = pd.read_csv("../data/RTA Dataset.csv")

In [3]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [4]:
df.shape

(12316, 32)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  str
 1   Day_of_week                  12316 non-null  str
 2   Age_band_of_driver           12316 non-null  str
 3   Sex_of_driver                12316 non-null  str
 4   Educational_level            11575 non-null  str
 5   Vehicle_driver_relation      11737 non-null  str
 6   Driving_experience           11487 non-null  str
 7   Type_of_vehicle              11366 non-null  str
 8   Owner_of_vehicle             11834 non-null  str
 9   Service_year_of_vehicle      8388 non-null   str
 10  Defect_of_vehicle            7889 non-null   str
 11  Area_accident_occured        12077 non-null  str
 12  Lanes_or_Medians             11931 non-null  str
 13  Road_allignment              12174 non-null  str
 14  Types_of_Junction            11429 non-null  str
 15  Road_surface_type            12144 non-null  str
 16  Road_surface_conditions      12316 non-null  str
 17  Light_conditions             12316 non-null  str
 18  Weather_conditions           12316 non-null  str
 19  Type_of_collision            12161 non-null  str
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  str
 23  Casualty_class               12316 non-null  str
 24  Sex_of_casualty              12316 non-null  str
 25  Age_band_of_casualty         12316 non-null  str
 26  Casualty_severity            12316 non-null  str
 27  Work_of_casuality            9118 non-null   str
 28  Fitness_of_casuality         9681 non-null   str
 29  Pedestrian_movement          12316 non-null  str
 30  Cause_of_accident            12316 non-null  str
 31  Accident_severity            12316 non-null  str
dtypes: int64(2), str(30)
memory usage: 6.7 MB

In [6]:
df.describe()

       Number_of_vehicles_involved  Number_of_casualties
count                 12316.000000          12316.000000
mean                      2.040679              1.548149
std                       0.688790              1.007179
min                       1.000000              1.000000
25%                       2.000000              1.000000
50%                       2.000000              1.000000
75%                       2.000000              2.000000
max                       7.000000              8.000000

In [7]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
for column in df.columns:
    print(column)
    print(df[column].unique())
    print("="*50)

Time
<ArrowStringArray>
['17:02:00',  '1:06:00', '14:15:00', '17:30:00', '17:20:00', '14:40:00',
 '17:45:00', '22:45:00',  '8:20:00', '15:10:00',
 ...
 '23:55:00', '15:58:00', '10:26:00',  '5:53:00',  '8:34:00', '22:11:00',
  '7:02:00',  '7:24:00', '19:18:00',  '2:47:00']
Length: 1074, dtype: str
==================================================
Day_of_week
<ArrowStringArray>
['Monday', 'Sunday', 'Friday', 'Wednesday', 'Saturday', 'Thursday', 'Tuesday']
Length: 7, dtype: str
==================================================
Age_band_of_driver
<ArrowStringArray>
['18-30', '31-50', 'Under 18', 'Over 51', 'Unknown']
Length: 5, dtype: str
==================================================
Sex_of_driver
<ArrowStringArray>
['Male', 'Female', 'Unknown']
Length: 3, dtype: str
==================================================
Educational_level
<ArrowStringArray>
[ 'Above high school', 'Junior high school',                  nan,
  'Elementary school',        'High school',            'Unknown',
         'Illiterate',  'Writing & reading']
Length: 8, dtype: str
==================================================
Vehicle_driver_relation
<ArrowStringArray>
['Employee', 'Unknown', 'Owner', nan, 'Other']
Length: 5, dtype: str
==================================================
Driving_experience
<ArrowStringArray>
[     '1-2yr', 'Above 10yr',     '5-10yr',      '2-5yr',          nan,
 'No Licence',  'Below 1yr',    'unknown']
Length: 8, dtype: str
==================================================
Type_of_vehicle
<ArrowStringArray>
[          'Automobile',  'Public (> 45 seats)',      'Lorry (41?100Q)',
                    nan, 'Public (13?45 seats)',       'Lorry (11?40Q)',
           'Long lorry',    'Public (12 seats)',                 'Taxi',
     'Pick up upto 10Q',         'Stationwagen',         'Ridden horse',
                'Other',                'Bajaj',                'Turbo',
           'Motorcycle',      'Special vehicle',              'Bicycle']
Length: 18, dtype: str
==================================================
Owner_of_vehicle
<ArrowStringArray>
['Owner', 'Governmental', nan, 'Organization', 'Other']
Length: 5, dtype: str
==================================================
Service_year_of_vehicle
<ArrowStringArray>
['Above 10yr', '5-10yrs', nan, '1-2yr', '2-5yrs', 'Unknown', 'Below 1yr']
Length: 7, dtype: str
==================================================
Defect_of_vehicle
<ArrowStringArray>
['No defect', nan, '7', '5']
Length: 4, dtype: str
==================================================
Area_accident_occured
<ArrowStringArray>
[              'Residential areas',                    'Office areas',
            '  Recreational areas',               ' Industrial areas',
                               nan,                           'Other',
                   ' Church areas',                  '  Market areas',
                         'Unknown',             'Rural village areas',
            ' Outside rural areas',                 ' Hospital areas',
                    'School areas', 'Rural village areasOffice areas',
              'Recreational areas']
Length: 15, dtype: str
==================================================
Lanes_or_Medians
<ArrowStringArray>
[                                               nan,
                                'Undivided Two way',
                                            'other',
                      'Double carriageway (median)',
                                          'One way',
  'Two-way (divided with solid lines road marking)',
 'Two-way (divided with broken lines road marking)',
                                          'Unknown']
Length: 8, dtype: str
==================================================
Road_allignment
<ArrowStringArray>
[               'Tangent road with flat terrain',
                                             nan,
 'Tangent road with mild grade and flat terrain',
                                   'Escarpments',
             'Tangent road with rolling terrain',
                       'Gentle horizontal curve',
     'Tangent road with mountainous terrain and',
 'Steep grade downward with mountainous terrain',
                           'Sharp reverse curve',
   'Steep grade upward with mountainous terrain']
Length: 10, dtype: str
==================================================
Types_of_Junction
<ArrowStringArray>
['No junction',     'Y Shape',    'Crossing',     'O Shape',       'Other',
     'Unknown',     'T Shape',     'X Shape',           nan]
Length: 9, dtype: str
==================================================
Road_surface_type
<ArrowStringArray>
[                   'Asphalt roads',                      'Earth roads',
                                nan, 'Asphalt roads with some distress',
                     'Gravel roads',                            'Other']
Length: 6, dtype: str
==================================================
Road_surface_conditions
<ArrowStringArray>
['Dry', 'Wet or damp', 'Snow', 'Flood over 3cm. deep']
Length: 4, dtype: str
==================================================
Light_conditions
<ArrowStringArray>
[               'Daylight',   'Darkness - lights lit',
  'Darkness - no lighting', 'Darkness - lights unlit']
Length: 4, dtype: str
==================================================
Weather_conditions
<ArrowStringArray>
[           'Normal',           'Raining', 'Raining and Windy',
            'Cloudy',             'Other',             'Windy',
              'Snow',           'Unknown',       'Fog or mist']
Length: 9, dtype: str
==================================================
Type_of_collision
<ArrowStringArray>
['Collision with roadside-parked vehicles',
          'Vehicle with vehicle collision',
         'Collision with roadside objects',
                  'Collision with animals',
                                   'Other',
                                'Rollover',
                      'Fall from vehicles',
              'Collision with pedestrians',
                              'With Train',
                                 'Unknown',
                                       nan]
Length: 11, dtype: str
==================================================
Number_of_vehicles_involved
[2 1 3 6 4 7]
==================================================
Number_of_casualties
[2 1 3 4 6 5 8 7]
==================================================
Vehicle_movement
<ArrowStringArray>
[     'Going straight',              'U-Turn',     'Moving Backward',
            'Turnover',       'Waiting to go',         'Getting off',
           'Reversing',             'Unknown',              'Parked',
            'Stopping',          'Overtaking',               'Other',
 'Entering a junction',                   nan]
Length: 14, dtype: str
==================================================
Casualty_class
<ArrowStringArray>
['na', 'Driver or rider', 'Pedestrian', 'Passenger']
Length: 4, dtype: str
==================================================
Sex_of_casualty
<ArrowStringArray>
['na', 'Male', 'Female']
Length: 3, dtype: str
==================================================
Age_band_of_casualty
<ArrowStringArray>
['na', '31-50', '18-30', 'Under 18', 'Over 51', '5']
Length: 6, dtype: str
==================================================
Casualty_severity
<ArrowStringArray>
['na', '3', '2', '1']
Length: 4, dtype: str
==================================================
Work_of_casuality
<ArrowStringArray>
[            nan,        'Driver',         'Other',    'Unemployed',
      'Employee', 'Self-employed',       'Student',       'Unknown']
Length: 8, dtype: str
==================================================
Fitness_of_casuality
<ArrowStringArray>
[nan, 'Normal', 'Deaf', 'Other', 'Blind', 'NormalNormal']
Length: 6, dtype: str
==================================================
Pedestrian_movement
<ArrowStringArray>
[                                                                                                                     'Not a Pedestrian',
                                                                                                       'Crossing from driver's nearside',
                                                         'Crossing from nearside - masked by parked or statioNot a Pedestrianry vehicle',
                                                                                                                      'Unknown or other',
                                                         'Crossing from offside - masked by  parked or statioNot a Pedestrianry vehicle',
                                                        'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing)',
                                                                                         'Walking along in carriageway, back to traffic',
                                                                                          'Walking along in carriageway, facing traffic',
 'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing) - masked by parked or statioNot a Pedestrianry vehicle']
Length: 9, dtype: str
==================================================
Cause_of_accident
<ArrowStringArray>
[                     'Moving Backward',
                           'Overtaking',
            'Changing lane to the left',
           'Changing lane to the right',
                          'Overloading',
                                'Other',
               'No priority to vehicle',
            'No priority to pedestrian',
                        'No distancing',
   'Getting off the vehicle improperly',
                     'Improper parking',
                            'Overspeed',
                   'Driving carelessly',
                'Driving at high speed',
                  'Driving to the left',
                              'Unknown',
                          'Overturning',
                             'Turnover',
 'Driving under the influence of drugs',
                        'Drunk driving']
Length: 20, dtype: str
==================================================
Accident_severity
<ArrowStringArray>
['Slight Injury', 'Serious Injury', 'Fatal injury']
Length: 3, dtype: str
==================================================

In [10]:
df["Accident_severity"].value_counts()

Accident_severity
Slight Injury     10415
Serious Injury     1743
Fatal injury        158
Name: count, dtype: int64